### ISSUE TITLE
Missing list of leads dropdown menu in Firefox Add-on

### ISSUE THREAD

**Issue by julietterobin** [hunter-io/browser-extension#11]
In the Firefox Add-on only, the list of leads is missing, which prevents using the "Save" buttons to save the leads to the user account.
![image](https://user-images.githubusercontent.com/20992234/106029972-a935ba00-609b-11eb-9da1-331b66465287.png)

**Comment by fgrante** [comment]
I can reproduce the bug; it seems we have CORS issues. @BastienL, any clue how we can solve it?

Here is what I get if I inspect the add-on in Firefox:

![image](https://user-images.githubusercontent.com/6638238/106357021-2da36980-6336-11eb-8b9f-5a00fff69f21.png)

**Comment by BastienL** [comment]
First intuition: could you ensure the extension provides the `Accept` header with the `application/json` value in all the requests to `api.hunter.io`?

**Comment by fgrante** [comment]
I made a few tests and changing the headers doesn't solve the issue. 

It seems that adding the domain name to the permissions solves it: https://github.com/hunter-io/browser-extension/commit/36e21ee1f627bf6c114f1a87bbdea588734d2888. Not sure why this API call was failing and not the others though.

The latest version 1.18.7 is now available to Firefox users.
